version: '3'
services:
  nginx:
    build:
      context: ./nginx
    env_file: ./env/nginx.env
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:rw
      - ./log:/var/log/nginx:rw
      - ./nginx/nginx.conf.temp:/tmp/nginx.conf.temp:ro
      - ./nginx/default.conf.temp:/tmp/default.conf.temp:ro
    command: >
      /bin/sh -c
      "envsubst
      '$$USER $$NGINX_LOG_DIR'
      </tmp/nginx.conf.temp > /etc/nginx/nginx.conf &&
      envsubst
      '$$APP_ENV $$SERVER_NAME $$CLIENT_MAX_BODY_SIZE'
      < /tmp/default.conf.temp > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
